import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import {
  ClerkProvider,
  RedirectToSignIn,
  SignOutButton,
  SignedIn,
  SignedOut,
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <SignedIn>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center px-6 py-4 bg-gray-800 text-white">
            <div className="text-2xl font-bold">
              <Link href="/">
                <span className="cursor-pointer hover:text-gray-400">MyApp</span>
              </Link>
            </div>
            <nav className="flex space-x-6">
              <Link href="/">
                <span className="cursor-pointer text-lg hover:text-gray-400">
                  Home
                </span>
              </Link>
              <Link href="/about">
                <span className="cursor-pointer text-lg hover:text-gray-400">
                  About
                </span>
              </Link>
              <Link href="/contact">
                <span className="cursor-pointer text-lg hover:text-gray-400">
                  Contact
                </span>
              </Link>
              <SignOutButton />
            </nav>
          </header>
          {children}
        </body>
      </html>
      </SignedIn>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
    </ClerkProvider>
  );
}
