import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Link from 'next/link';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-between items-center px-6 py-4 bg-gray-800 text-white">
          <div className="text-2xl font-bold"></div>
          <nav className="flex space-x-6">
            <Link href="/">
              <span className="cursor-pointer text-lg hover:text-gray-400">
                Home
              </span>
            </Link>
            <Link href="/backoffice">
              <span className="cursor-pointer text-lg hover:text-gray-400">
                Overview
              </span>
            </Link>
            <Link href="/backoffice/finance">
              <span className="cursor-pointer text-lg hover:text-gray-400">
                Finance
              </span>
            </Link>
            <Link href="/backoffice/menu">
              <span className="cursor-pointer text-lg hover:text-gray-400">
                Menu
              </span>
            </Link>
            <Link href="/backoffice/support">
              <span className="cursor-pointer text-lg hover:text-gray-400">
                Support
              </span>
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
